version: '3.6'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    platform: linux/amd64
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "80:3000"
      - "8002:8002"
    volumes:
      - ./src:/app:delegated
    stdin_open: true
    tty: true

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    environment:
      # save logs on disk
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - ./docker/mailhog/logs:/tmp:delegated
    ports:
      - '1025:1025'
